import Footer from "@/Components/Footer/Footer";
import "./globals.css";
import Nav from "@/Components/Navbar/Nav";
import { Cairo } from "next/font/google";

const cairo = Cairo({
  subsets: ["latin"],
  weight: ["300", "400", "700"], // حدد الأوزان التي تحتاجها
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <body className={cairo.className}>
        <Nav />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
